### ISSUE TITLE
训练时出现的错误

### ISSUE THREAD

**Issue by Garbobro** [Onion12138/CasRelPyTorch#16]
我把数据集换成了完整的duie百度数据集，在训练的时候第一轮训练到10%时出错：
Epoch 1/10:  10%|▉         | 10600/106960 [37:13<5:41:25,  4.70it/s, loss:0.09831]
  0%|          | 0/20652 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\NLP\CasRelPyTorch-master\Run.py", line 63, in <module>
    trainer.train()
  File "D:\Anaconda3\lib\site-packages\fastNLP\core\trainer.py", line 622, in train
    raise e
  File "D:\Anaconda3\lib\site-packages\fastNLP\core\trainer.py", line 615, in train
    self._train()
  File "D:\Anaconda3\lib\site-packages\fastNLP\core\trainer.py", line 720, in _train
    self.callback_manager.on_epoch_end()
  File "D:\Anaconda3\lib\site-packages\fastNLP\core\callback.py", line 314, in wrapper
    returns.append(getattr(callback, func.__name__)(*arg))
  File "C:\Users\Administrator\Desktop\NLP\CasRelPyTorch-master\model\callback.py", line 30, in on_epoch_end
    precision, recall, f1_score = metric(self.data_iter, self.rel_vocab, self.config, self.model)
  File "C:\Users\Administrator\Desktop\NLP\CasRelPyTorch-master\model\evaluate.py", line 71, in metric
    gold_triples = set(to_tuple(batch_y['triples'][0]))
TypeError: unhashable type: 'dict'

Process finished with exit code 1
请问能解答一下哪里的问题吗，谢谢了

**Comment by yangsirui990402** [comment]
你好，我也遇到了这个问题，请问你解决了吗
